### ISSUE TITLE
pre-release / release-candidate suffix

### ISSUE THREAD

**Issue by favoyang** [coryleach/UnityAsync#6]
Hi @coryleach,

Favo from openupm. I noticed an issue for your Git tag naming may affect your build. Take this repository as an example:

| Git tag | package.json version | 
| --- | --- |
| 1.0.4-a | 1.0.4 |
| 1.0.4 | 1.0.4 |

The problem is that you're using the `-a` (alpha?) as a release candidate / pre-release suffix, but you didn't update the package.json's version. As a result, the tag `1.0.4-a` takes the spot on the registry with version `1.0.4` because it came earlier, then the tag `1.0.4` failed because of version conflict.

I have fixed the issue, by adding `-a` as the Git tag ignore pattern to ignore it (https://github.com/openupm/openupm/commit/c4c2d8e65e6a6ce775dedac9254d5eb9c0c780f6, https://github.com/openupm/openupm/commit/fcfb863f3cebdc39d8ae772e2c08d39baceea328, https://github.com/openupm/openupm/commit/74404435bda9713c1a4d80e0091a0305627eb429, https://github.com/openupm/openupm/commit/20ca6d152c59a45ff9cae3613f0853deff88067e), then I unpublished the wrong release generated by the `-a` suffix.

Because you have quite a few packages published there, to solve the issue completely:
- Either you always update the packgae.json to match your Git tag
- Or I need to know your preferred suffix for pre-release. e.g. will you use `-a` only or maybe `-b`? I would suggest you use `-rc[0-9]` instead.

**Comment by coryleach** [comment]
Thanks for letting me know! I am currently working on better formalizing the way I handle development and releases. I'll make sure the package's version is kept in sync with the GitHub tag from now on.
